name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: javac https://github.com/vivektwins/Practice-code/blob/master/src/Test/fetchNestedJSONfromArray.java
